"""Bridge scripts for commercial EDA tools (Calibre, IC Validator).

OpenLithoHub does not implement full DRC — these helpers emit minimal,
human-editable rule decks that load an exported ``.oas`` and run the most
basic checks (min width, min spacing). The intent is to remove the friction
of "I have OASIS, now what?" for layout engineers, not to replace a real
sign-off deck.

The emitted files are pure text. No EDA tool is invoked here.
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path


@dataclass(frozen=True)
class BridgeRules:
    """Minimal DRC rules used by the emitted templates."""

    min_width_nm: float
    min_spacing_nm: float
    layer: int = 1
    datatype: int = 0


_CALIBRE_TEMPLATE = """\
// Auto-generated by OpenLithoHub — minimal Calibre nmDRC rule deck.
// Edit freely; this is a starting point, not a sign-off deck.

LAYOUT PATH "{oasis_path}"
LAYOUT PRIMARY "{cell_name}"
LAYOUT SYSTEM OASIS

DRC RESULTS DATABASE "{cell_name}.results.db" ASCII
DRC SUMMARY REPORT "{cell_name}.summary.rep"

PRECISION 1000
RESOLUTION 1

LAYER MASK {layer} DATATYPE {datatype}

mask = COPY MASK

min_width {{
   @ Minimum width on MASK is {min_width_nm} nm.
   INTERNAL mask < {min_width_nm} ABUT < 90 SINGULAR REGION
}}

min_spacing {{
   @ Minimum spacing on MASK is {min_spacing_nm} nm.
   EXTERNAL mask < {min_spacing_nm} ABUT < 90 SINGULAR REGION
}}
"""

_ICV_TEMPLATE = """\
// Auto-generated by OpenLithoHub — minimal Synopsys IC Validator rule file.
// Run with: icv -i {oasis_path} -f OASIS -top {cell_name} <this_file>.rs

layout("{oasis_path}", OASIS, "{cell_name}");

mask = assign({{ {{ {layer}, {datatype} }} }});

min_width = internal1(mask, < {min_width_nm});
output(min_width, {{ {{ 1000, 0 }} }}, "min_width_violations");

min_spacing = external1(mask, < {min_spacing_nm});
output(min_spacing, {{ {{ 1001, 0 }} }}, "min_spacing_violations");
"""

_RUN_README = """\
# Running the {tool} bridge deck

Generated by OpenLithoHub for `{oasis_path}` (cell `{cell_name}`).

## Calibre

```sh
calibre -drc -hier {svrf_path}
```

## IC Validator

```sh
icv -dp 4 -i {oasis_path} -f OASIS -top {cell_name} {runset_path}
```

These decks only check minimum width / minimum spacing. Replace with your
foundry's qualified deck before sign-off.
"""


def emit_calibre_svrf(
    oasis_path: str | Path,
    rules: BridgeRules,
    *,
    cell_name: str = "TOP",
    output_path: str | Path | None = None,
) -> Path:
    """Emit a minimal Calibre nmDRC ``.svrf`` rule deck next to the OASIS file."""
    oasis_path = Path(oasis_path)
    out = Path(output_path) if output_path else oasis_path.with_suffix(".svrf")
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(
        _CALIBRE_TEMPLATE.format(
            oasis_path=str(oasis_path),
            cell_name=cell_name,
            layer=rules.layer,
            datatype=rules.datatype,
            min_width_nm=rules.min_width_nm,
            min_spacing_nm=rules.min_spacing_nm,
        ),
        encoding="utf-8",
    )
    return out


def emit_icv_runset(
    oasis_path: str | Path,
    rules: BridgeRules,
    *,
    cell_name: str = "TOP",
    output_path: str | Path | None = None,
) -> Path:
    """Emit a minimal Synopsys IC Validator runset next to the OASIS file."""
    oasis_path = Path(oasis_path)
    out = Path(output_path) if output_path else oasis_path.with_suffix(".rs")
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(
        _ICV_TEMPLATE.format(
            oasis_path=str(oasis_path),
            cell_name=cell_name,
            layer=rules.layer,
            datatype=rules.datatype,
            min_width_nm=rules.min_width_nm,
            min_spacing_nm=rules.min_spacing_nm,
        ),
        encoding="utf-8",
    )
    return out


def emit_bridge_bundle(
    oasis_path: str | Path,
    rules: BridgeRules,
    *,
    cell_name: str = "TOP",
) -> dict[str, Path]:
    """Emit Calibre + IC Validator templates and a short README for the bundle."""
    oasis_path = Path(oasis_path)
    svrf = emit_calibre_svrf(oasis_path, rules, cell_name=cell_name)
    runset = emit_icv_runset(oasis_path, rules, cell_name=cell_name)
    readme = oasis_path.with_suffix(".bridge.md")
    readme.write_text(
        _RUN_README.format(
            tool="Calibre / IC Validator",
            oasis_path=str(oasis_path),
            cell_name=cell_name,
            svrf_path=str(svrf),
            runset_path=str(runset),
        ),
        encoding="utf-8",
    )
    return {"svrf": svrf, "icv": runset, "readme": readme}
